server:
  port: 8070

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order
    username: postgres
    password: 85192577
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  config:
    customer-url: http://localhost:8222/api/v1/customer
    product-url: http://localhost:8222/api/v1/product
    payment-url: http://localhost:8222/api/v1/payments

